[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kawa"
version = "0.1.0"
description = "Useless cute little CLI tool"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "cherrblyria" }]

[project.scripts]
kawa = "kawa.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/kawa"]

[dependency-groups]
dev = ["pyinstaller>=6.10", "ruff>=0.6"]

[tool.ruff]
src = ["src"]
